### PR TITLE
feat: http-client

### PR DESCRIPTION
**Pull request by HongLinLiao**
- add http client package: axios & swr
- add api proxy internal route & http-proxy-middleware package (remaining work: add backend endpoint in env)
- add axios context & provider container & hook
- add http request wrapper

### CODE REVIEW

**Comment by HongLinLiao** [comment]
Hi @Parkerhiphop, please help me to check I need to attach any label or project in PR?

**Comment by HongLinLiao** [comment]
I got an error from `docker compose build`
```
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
```

But run `npm run build` is success.

**Comment by HongLinLiao** [comment]
I clear docker cache fixed this error.

**Review by JimmyHou024 — APPROVED** [review]

**Comment by Parkerhiphop** [comment]
> I did not experience any issue with 'Docker compose build'.
> 
> But I encountered _HOT RELOAD_ failure with `docker compose up` command, and use `npm run dev` is success.

**Review by Parkerhiphop — APPROVED** [review]
LGTM

**Pull request merged**
